server:
   port: 8082
spring:
   application:
      name: MircroService-Item
   profiles:
      active: test
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.99.0.4:3306/emart-main?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: emart
      password: 123456
   jpa:
      hibernate:
         database-platform: org.hibernate.dialect.MySQLDialect
         ddl-auto: update
         show-sql: true
   servlet:
      multipart:
        max-file-size: 5MB
logging:
  level:
    org:
      hibernate:
        SQL: ERROR
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://172.99.0.2:9001/eureka/
picture:
  upload-path: C://eMart//pictures//