server:
   port: 8083
spring:
   application:
      name: MircroService-Item
   profiles:
      active: test
   zipkin:
      baseUrl: http://localhost:8080
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/emart-main?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: root
   jpa:
      hibernate:
         database-platform: org.hibernate.dialect.MySQLDialect
         ddl-auto: update
         show-sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG