server:
  port: 8080
spring:
  application:
    name: zuul
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
zuul:
  shouldNotFilter: /user,/picture
  routes:
    user:
      path: /user/**
      service-id: MircroService-User
      strip-prefix: false
    item:
      path: /item/**
      service-id: MircroService-Item
      strip-prefix: false
    transaction:
      path: /transaction/**
      service-id: MircroService-Transaction
      strip-prefix: false
    mast:
      path: /mast/**
      service-id: MircroService-Mast
      strip-prefix: false
    picture:
      path: /picture/**
      service-id: MircroService-Item
      strip-prefix: false
token:
  secret: emart
  expire-time: 720
logging:
  level:
    root: info
