server:
  port: 8085
spring:
  application:
    name: zuul
  servlet:
    multipart:
      max-file-size: 5MB
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://172.99.0.2:9001/eureka/
zuul:
  shouldNotFilter: /user/**,/picture/**,/item,/item/search/**,/item/detail/**,/manufactur
  routes:
    user:
      path: /user/**
      service-id: MircroService-User
      strip-prefix: false
    item:
      path: /item/**
      service-id: MircroService-Item
      strip-prefix: false
    picture:
      path: /picture/**
      service-id: MircroService-Item
      strip-prefix: false
    transaction:
      path: /transaction/**
      service-id: MircroService-Transaction
      strip-prefix: false
    cart:
      path: /cart/**
      service-id: MircroService-Transaction
      strip-prefix: false
    history:
      path: /history/**
      service-id: MircroService-Transaction
      strip-prefix: false
    report:
      path: /report/**
      service-id: MircroService-Transaction
      strip-prefix: false
    discount:
      path: /discount/**
      service-id: MircroService-Mast
      strip-prefix: false
    category:
      path: /category/**
      service-id: MircroService-Mast
      strip-prefix: false
    manufactur:
      path: /manufactur/**
      service-id: MircroService-Mast
      strip-prefix: false
token:
  secret: emart
  expire-time: 720
logging:
  level:
    root: ERROR
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 30000
