server:
  port: 8080
spring:
  application:
    name: zuul
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
zuul:
  routes:
    MircroService-User: /user/**
    MircroService-Item: /item/**
    MircroService-Transaction: /transaction/**
    MircroService-Mast: /mast/**
  noTokenValid: /user
