server:
  port: 8080
spring:
  application:
    name: zuul
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
zuul:
  routes:
    gateway-user:
      path: /user/**
      serviceId: MircroService-User
    gateway-item:
      path: /item/**
      serviceId: MircroService-Item
    gateway-transaction:
      path: /transaction/**
      serviceId: MircroService-Transaction
    gateway-mast:
      path: /mast/**
      serviceId: MircroService-Mast
