server:
   port: 8081
spring:
   application:
      name: MircroService-User
   messages:
       basename: i18n/messages
       encoding: UTF-8
   profiles:
      active: test
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.99.0.4:3306/emart-main?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: emart
      password: 123456
   jpa:
      hibernate:
         database-platform: org.hibernate.dialect.MySQLDialect
         ddl-auto: update
         show-sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
token:
  secret: emart
  expire-time: 720 #minutes
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://172.99.0.2:9001/eureka/